import type { SetterRenderer } from "./types";
import {
  BasicInputNumberSetter,
  BasicInputSetter,
  BasicSelectSetter,
  BasicSwitchSetter,
  BasicTextareaSetter,
  CheckboxSetter,
  DatePickerSetter,
  DateTimePickerSetter,
  FallbackInputSetter,
  ImageSetter,
  RadioSetter,
  ReadonlyJsonSetter,
  TimePickerSetter,
} from "./setters/basic";
import {
  BreadcrumbItemsSetter,
  DescriptionsItemsSetter,
  DropdownMenuItemsSetter,
  ListDataSourceSetter,
  MenuItemsSetter,
  OptionListSetter,
  StepsItemsSetter,
  TableActionsSetter,
  TableColumnsSetter,
  TableDataSourceSetter,
  TabsItemsSetter,
  TreeDataSetter,
} from "./setters/collections";

export const setterRegistry: Record<string, SetterRenderer> = {
  input: BasicInputSetter,
  select: BasicSelectSetter,
  switch: BasicSwitchSetter,
  inputNumber: BasicInputNumberSetter,
  textarea: BasicTextareaSetter,
  image: ImageSetter,
  readonlyJson: ReadonlyJsonSetter,
  optionList: OptionListSetter,
  breadcrumbItems: BreadcrumbItemsSetter,
  stepsItems: StepsItemsSetter,
  tabsItems: TabsItemsSetter,
  dropdownMenuItems: DropdownMenuItemsSetter,
  menuItems: MenuItemsSetter,
  descriptionsItems: DescriptionsItemsSetter,
  listDataSource: ListDataSourceSetter,
  tableColumns: TableColumnsSetter,
  tableDataSource: TableDataSourceSetter,
  tableActions: TableActionsSetter,
  treeData: TreeDataSetter,
  radio: RadioSetter,
  checkbox: CheckboxSetter,
  datePicker: DatePickerSetter,
  timePicker: TimePickerSetter,
  dateTimePicker: DateTimePickerSetter,
};

export { FallbackInputSetter };
